name = "m25"
version = "1.0.0"
description = "A background job library for Gleam and Postgres!"
licences = ["MIT"]
repository = { type = "github", user = "Pevensie", repo = "m25" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.60.0 and < 2.0.0"
pog = ">= 4.1.0 and < 5.0.0"
lifeguard = ">= 4.0.0 and < 5.0.0"
gleam_erlang = ">= 1.0.0 and < 2.0.0"
gleam_otp = ">= 1.0.0 and < 2.0.0"
gleam_json = ">= 3.0.1 and < 4.0.0"
gleam_time = ">= 1.2.0 and < 2.0.0"
youid = ">= 1.5.0 and < 2.0.0"
logging = ">= 1.3.0 and < 2.0.0"
snag = ">= 1.1.0 and < 2.0.0"
filepath = ">= 1.1.2 and < 2.0.0"
simplifile = ">= 2.3.0 and < 3.0.0"
gtempo = ">= 7.2.2 and < 8.0.0"
glint = ">= 1.2.1 and < 2.0.0"
argv = ">= 1.0.2 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
squirrel = ">= 4.2.0 and < 5.0.0"
