name = "m25"
version = "1.0.0"
description = "A background job library for Gleam and Postgres!"
licences = ["MIT"]
repository = { type = "github", user = "Pevensie", repo = "m25" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.60.0 and < 2.0.0"
pog = ">= 3.2.0 and < 4.0.0"
lifeguard = ">= 4.0.0 and < 5.0.0"
gleam_erlang = ">= 1.0.0 and < 2.0.0"
gleam_otp = ">= 1.0.0 and < 2.0.0"
gleam_json = ">= 3.0.1 and < 4.0.0"
gleam_time = ">= 1.2.0 and < 2.0.0"
youid = ">= 1.5.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
squirrel = ">= 3.0.4 and < 4.0.0"
