insert into m25.job (
    id,
    queue_name,
    scheduled_at,
    input,
    timeout,
    attempt,
    max_attempts,
    original_attempt_id,
    previous_attempt_id,
    retry_delay,
    unique_key
    ) values (
    $1,
    $2,
    to_timestamp($3),
    $4,
    make_interval(secs => $5),
    $6,
    $7,
    $8,
    $9,
    make_interval(secs => $10),
    $11
) returning
    id,
    queue_name,
    created_at::timestamp,
    scheduled_at::timestamp,
    input,
    reserved_at::timestamp,
    started_at::timestamp,
    cancelled_at::timestamp,
    finished_at::timestamp,
    extract(epoch from timeout)::int as timeout,
    status,
    output,
    deadline::timestamp,
    latest_heartbeat_at::timestamp,
    failure_reason,
    error_data,
    attempt,
    max_attempts,
    original_attempt_id,
    previous_attempt_id,
    extract(epoch from retry_delay)::int as retry_delay,
    unique_key;
