name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.1.2"
          gleam-version: "1.11.1"
          rebar3-version: "3"
          # elixir-version: "1"
      - run: gleam deps download
      - run: gleam run -m m25 migrate --apply
      # TODO: Re-add this once Squirrel generates formatted SQL
      # - run: gleam run -m squirrel check
      #   env:
      #     DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/postgres"
      - run: gleam test
      - run: gleam format --check src test
